version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8765"
      - "5432:5432"
    # environment:
    #   - RDS_HOST=host.docker.internal
    #   - RDS_NAME=postgres
    #   - RDS_USER=postgres
    #   - RDS_PASSWORD=""
    #   - PORT=8765
    env_file:
      - ./.env.dev
