version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
    command: gunicorn djangoproject.wsgi:application --bind 0.0.0.0:8765
    volumes:
      - .:/app
    ports:
      - "8000:8765"
      - "5432:5432"
    env_file:
      - ./.env.prod
