version: "3.9"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod

    command: gunicorn django_application.wsgi:application --bind 0.0.0.0:8000

    ports:
      - "8000:8000"
      - "5432:5432"
    env_file:
      - ./.env.prod
